apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init-db
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: quay.io/astronomer/ap-airflow:2.9.0-buster
          command: ["airflow", "db", "init"]
          envFrom:
            - configMapRef:
                name: airflow-config
          env:
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: fernet-key
      restartPolicy: OnFailure